title: LSX-UniWue
logo: /assets/img/LSX.png

# email: your-email@example.com
description: Chair of Data Science at JMU Wuerzburg.

domain: lsx-uniwue.github.io
url: https://lsx-uniwue.github.io

twitter_username: datascience_jmu
github_username:  LSX-UniWue

# Build settings
remote-theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
